# Generated by Django 5.1.7 on 2026-04-17 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_livro_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='autor',
        ),
    ]
